// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj1zOtHtFzsPqdlUHgvlKFAWbDYSkSTE8',
    appId: '1:444102537841:web:3b5050446c1ea8d666a1d0',
    messagingSenderId: '444102537841',
    projectId: 'my-project-flutter-47201',
    authDomain: 'my-project-flutter-47201.firebaseapp.com',
    storageBucket: 'my-project-flutter-47201.firebasestorage.app',
    measurementId: 'G-3DWRQBR62E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnM0EF3jFamcMWH4IMPrN6itXrWt5r598',
    appId: '1:444102537841:android:406ae6d9481d97e066a1d0',
    messagingSenderId: '444102537841',
    projectId: 'my-project-flutter-47201',
    storageBucket: 'my-project-flutter-47201.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB8yy3L2OQxF_NVzklvBhGfKwS_CpIFOE',
    appId: '1:444102537841:ios:1db38ab5e673966f66a1d0',
    messagingSenderId: '444102537841',
    projectId: 'my-project-flutter-47201',
    storageBucket: 'my-project-flutter-47201.firebasestorage.app',
    androidClientId: '444102537841-e115e3fg6b0m8slrg3060p4ogucvfpfc.apps.googleusercontent.com',
    iosClientId: '444102537841-8dlsurt0f4jg68pk65lfav1qnmgh0jq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.th4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB8yy3L2OQxF_NVzklvBhGfKwS_CpIFOE',
    appId: '1:444102537841:ios:1db38ab5e673966f66a1d0',
    messagingSenderId: '444102537841',
    projectId: 'my-project-flutter-47201',
    storageBucket: 'my-project-flutter-47201.firebasestorage.app',
    androidClientId: '444102537841-e115e3fg6b0m8slrg3060p4ogucvfpfc.apps.googleusercontent.com',
    iosClientId: '444102537841-8dlsurt0f4jg68pk65lfav1qnmgh0jq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.th4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj1zOtHtFzsPqdlUHgvlKFAWbDYSkSTE8',
    appId: '1:444102537841:web:28343bcba9a976dd66a1d0',
    messagingSenderId: '444102537841',
    projectId: 'my-project-flutter-47201',
    authDomain: 'my-project-flutter-47201.firebaseapp.com',
    storageBucket: 'my-project-flutter-47201.firebasestorage.app',
    measurementId: 'G-87D8PKEXMC',
  );
}
